version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: image.push
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data: